#: Allow other programs to control kitty
allow_remote_control yes
listen_on unix:/tmp/kitty

#: Avoid TERMINFO issues with sudo
shell_integration no-sudo,no-title

#: Terminal identity
term xterm-kitty

#: Default shell
shell zsh --login
editor nvim

#: Appearance
font_size 15
font_family JetBrainsMono Nerd Font Mono

scrollback_lines 10000
copy_on_select yes

hide_window_decorations titlebar-only
window_padding_width 0 0 0 0
confirm_os_window_close 0
enable_audio_bell no

macos_option_as_alt right

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0
cursor_stop_blinking_after 0
cursor_trail_decay 0.01 0.5
cursor_trail_start_threshold 0

background_opacity 0.95
background_blur 10

include theme.conf

#: Tab bar
# tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
# tab_title_template "{session_name} {title}"

#: Only show tabs for current session (or no session)
tab_bar_filter session:~ or session:^$
